### ISSUE TITLE
Abroad India not working

### ISSUE THREAD

**Issue by crazyontech** [Gujal00/GujalKodiWork#1]
I am not able to access the Tamil Live channels using Abroad India...Is it something which can be fixed?

**Comment by Gujal00** [comment]
Abroad India mostly works. Sometimes you have to try the same channel twice.
Please  check if the channel works on abroadindia website and then report which stream is not working in the addon

**Comment by crazyontech** [comment]
Ok. Initially the addon kept suggesting that I need to login into the Abroad India in the same network. But somehow this evening it got fixed by itself.
Thanks
