### ISSUE TITLE
hey

### ISSUE THREAD

**Issue by janu1988** [Gujal00/GujalKodiWork#10]
Hey bro , thanks for wonderful work.
please add http://www.hotstar.com/ , https://einthusan.tv/ and http://www.tamilserials.tv/
and youtube if possible, it  is easy to download music and videos with you download options, thanks for it.

**Comment by Gujal00** [comment]
hotstar and eintusan have their dedicated and working addons already. So won't look into that yet.
Youtube is a Kodi official addon, so won't work on that either
Will take a look at tamilserials site

**Comment by alikader** [comment]
hi, 
Any problem with Deccan Delight, after the update.  All files disappeared.

**Comment by janu1988** [comment]
Hey Bro please add http://tamilrage.com 
Hotstar and Einthusan addons not working. can you add the sites too please?
Thank you!

**Comment by Gujal00** [comment]
@janu1988 
tamilserials.tv scraper added in DD 1.4.8 release
