### ISSUE TITLE
Sitescraper request

### ISSUE THREAD

**Issue by rubanrex** [Gujal00/GujalKodiWork#13]
Could you fix thoptv scrapers. Also is it possible to include hyfytv.in please

**Comment by Gujal00** [comment]
Most of the thoptv channels don't work on the website. let me know if you find something on their website that is working and not working on the addon.
Will take a look at hyfytv.in when time permits

**Comment by rubanrex** [comment]
Thanks for this amazing add-on.in watch.thoptv.com, Tamil channels are working including sun TV HD, k TV hd, Aditya, Vijay TV hd etc but it's not working in the add-on.

**Comment by Gujal00** [comment]
Lot of channels (Jaya, Kalaignar, etc) still don't work on the site. Will release a fix when everything works on the site.

**Comment by Gujal00** [comment]
@rubanrex 
released a fix for thop in 1.46, but still lot of channels Jaya, Kalaignar, etc are not working on site, so wont work on addon,

**Comment by rubanrex** [comment]
Thanks a lot man :)

**Comment by Gujal00** [comment]
@rubanrex 
hyfytv.in will be in the next release

**Comment by rubanrex** [comment]
Thanks a ton. You're amazing

**Comment by mujunk** [comment]
Thanks a lot. Highly appreciated.
