### ISSUE TITLE
MHDTV not working

### ISSUE THREAD

**Issue by rony007dennis** [Gujal00/GujalKodiWork#15]
Hi
MHDTV is not working - Malayalam channels.

**Comment by Gujal00** [comment]
Yes, it has been that way for a couple of months as the site is now enforcing login.

**Comment by rony007dennis** [comment]
I tried accessing the website and it seems to work without signing in. 
for example:
http://mhdtvlive.co.in/video/mazhavil-manorama-hd/

if it requires sign in can a feature be added to save user name and password from the user side so that when we try to access the website, it would use the saved user name and password. 

other live stream websites does not seem to have enough channels. :(

**Comment by Gujal00** [comment]
Not interested in scraping any site which requires login. So won't fix.

**Comment by Gujal00** [comment]
@rony007dennis 
Okay v1.4.6 is released with MHDTV fixes
You need to setup username and password in the settings and then DD will use your logon details to access MHDTV
