### ISSUE TITLE
Sitescraper request tamilrage

### ISSUE THREAD

**Issue by janu1988** [Gujal00/GujalKodiWork#16]
Hey Bro please add http://tamilrage.com , http://tamiltv.online/ , http://www.tamildbox.net
Einthusan addons not working. can you add the sites too please?
Thank you!

**Comment by Gujal00** [comment]
Einthusan 1.3.9 is working fine. If it is not working for you raise a issue in Einthusan github.
tamildbox is part of tamilgun scraper, so no need to add it.
Will take a look at other two

**Comment by Gujal00** [comment]
tamiltv.online is just loading ads on top of thoptv to show the stream. DD already has thoptv, so no point adding tamiltv.online
tamilrage.com is using cloudflare ddos protection. DD doesnt have the functionality to scrape such sites yet. Will take time to do it.

**Comment by janu1988** [comment]
Ok Thanks Bro ;)

**Comment by Gujal00** [comment]
@janu1988 
Had a look at tamilrage, the pages contain only one link and on most pages the link is dead. Doesn't look like a worthwhile site to add to DD.
Closing this for now
