### ISSUE TITLE
Thop TV not working

### ISSUE THREAD

**Issue by mujunk** [Gujal00/GujalKodiWork#17]
Its working fine on the website http://thoptv.stream/
Does not work on the Kodi Addon.

**Comment by Gujal00** [comment]
Lot of channels still don't work on the site. Will release a fix when everything works on the site.

**Comment by mujunk** [comment]
Thank you. thoptv and hyfytv.in seem to be leeching from the jiotv app/website,
Every Channel I checked seem to be working right now. 
No rush though. Will wait for your fix.

**Comment by Gujal00** [comment]
Did you check any of the Jaya network channels or the Kalaignar network channels. They don't work as they are not from jiotv site

**Comment by mujunk** [comment]
On that note. How feasible is a "jiotv live" section? Their android app is working without any login
Addons like StreamHub have an "android api" section. Could something similar be done here?
https://archive.org/download/repository.streamhub

**Comment by Gujal00** [comment]
AFAIK jiotv app works only if connected to Jio 4G network. Don't think it is possible to do it from outside their network

**Comment by Gujal00** [comment]
v1.4.5 released with the fix. Let's see how long before thoptv change the code again.

**Comment by mujunk** [comment]
Thanks for the update. working fine now.
I have the JioTv app on my android phone and works fine without login or Jio sim. I live outside India. App version is 1.0

**Comment by Gujal00** [comment]
Email me the apk file and I will take a look and see if the api calls can be pulled from it

**Comment by mujunk** [comment]
Try this one https://file.io/58heJQ

**Comment by Gujal00** [comment]
@mujunk 
It is a fake app which has nothing to do with Jio.
All the streams are pulled from http://nextvnow.live/ and none are jiostreams

**Comment by mujunk** [comment]
Thanks for pointing that out. Looks like an official fake by Jio ;)

![screenshot_2017-12-29-10-38-15](https://user-images.githubusercontent.com/27666937/34435366-e8ae267e-ec84-11e7-8c25-6b5597d731c8.png)

**Comment by freeiptv1** [comment]
@Gujal00 
How to make these streams work with KODI. Any ideas? [http://freeiptv.ga/tv.php?channel=B4U_Movies&progid=182](http://freeiptv.ga/tv.php?channel=B4U_Movies&progid=182)
I have limited bandwidth. This page is just for a demo

**Comment by Gujal00** [comment]
They already work in Deccan Delight under NextTv
