### ISSUE TITLE
Fresh Install not working

### ISSUE THREAD

**Issue by kirupromo** [Gujal00/GujalKodiWork#19]
i have deccan delight addon running on an existing fire tv box. Thank you for your work.
However when i tried doing a fresh install for a friend i'm getting unable to install addon error.
Tried the repository method and the direct zip file method.
Something is wrong. Kindly help out.

Environment: Kodi Krypton, Amazon Fire Tv Stick.

**Comment by Gujal00** [comment]
Direct zip method won’t work unless dependencies are installed. Always use repository method. What version of repository are you using. If it is not 1.6 it will not work either.
If still not working, upload the kodi log file after the failed installation to pastebin and give the link here

**Comment by kirupromo** [comment]
apparently it was a corrupt zip file that was copied over ftp that caused it (thanks to logs getdirectory error)
please close this issue.
