### ISSUE TITLE
Missing tamilgun tamilyogi links

### ISSUE THREAD

**Issue by rubanrex** [Gujal00/GujalKodiWork#2]
Hello
Thanks for intimating the github link. Tamilgun n tamilyogi movie links are missing for some reason. Sorry for troubling you again and thank you for being an awesome developer.

**Comment by Gujal00** [comment]
Fixed in https://github.com/Gujal00/GujalKodiWork/commit/3ec55cb5f1a4c197d25626f9bea39176bf8d13fe
v1.2.4 released
