### ISSUE TITLE
http://www.tamilserials.tv/

### ISSUE THREAD

**Issue by janu1988** [Gujal00/GujalKodiWork#20]
Hi bro, 
from http://www.tamilserials.tv/ youtube links are not showing in kodi,
but on website its working fine. 
ex: http://www.tamilserials.tv/sun-tv-serials/04-01-2018-vaani-rani-serial/

just to let you know.
Thanks for adding the site :)

**Comment by Gujal00** [comment]
Yep, will fix in the next release

**Comment by Gujal00** [comment]
Fixed in 1.4.9 release
