### ISSUE TITLE
URL Resolver Issue - Deccan Delight

### ISSUE THREAD

**Issue by rmj2018** [Gujal00/GujalKodiWork#21]
Hi, I have the latest versions (which I just re-confirmed) of your repositories, but been getting URL resolver related errors lately when trying malayalam movies in TOR malayalam, Olangal etc. These URL resolver errors vary from  "SSL verification failed", "URL not found" and so on. Is this like a known issue? I have Kodi 17.6 Krypton on Amazon FireTV. 

Thank you!

**Comment by Gujal00** [comment]
First test is to access those sites from web browser and confirm that the links you are trying to play work on the browser.
If playing in browser, then need Kodi logfile to look at what's happening
After you try a few with failures, upload the log file to pastebin and give the link here.

**Comment by rmj2018** [comment]
Thank you for your response.
looks like the links are not working from the browser also, all invalid SSL cert related issues. A lot of the malayalam links have this problem. 
By the way, just in general, is there a particular version of URL resolver that works best with deccan delight or will just the latest version be fine?

**Comment by Gujal00** [comment]
If you have installed gujal repository, then it installs the current version of URL resolver when you install deccan delight and keeps both up to date.
