### ISSUE TITLE
desi tashan /sony

### ISSUE THREAD

**Issue by rrosajp** [Gujal00/GujalKodiWork#22]
hi gujal
can u pl rework on desi tushan  @ desit .py scraper to have poras in sony channel it have old /new show but not current  "poras"
thanks

**Comment by Gujal00** [comment]
Porus is not listed in http://www.desi-tashan.org/sony-tv/
So the scraper is not picking it up.

**Comment by rrosajp** [comment]
i know it it on http://www.desi-tashan.org/category/sony-tv/porus/ or on main page as http://www.desi-tashan.org if u can it's appreciated.

**Comment by Gujal00** [comment]
Not possible, because if I change the scraping to look for serials from main page, it will not show Star Jalsha channel completely. So unless the show gets listed under its channel page, it wont be scraped.

**Comment by Gujal00** [comment]
DT have fixed their website code and now Porus is listed under Sony. DD is correctly picking up the pages now
