### ISSUE TITLE
Deccan delight error

### ISSUE THREAD

**Issue by yesosuresh** [Gujal00/GujalKodiWork#24]
Hi, 
I've encountered this error after updating your repo. Kindly check. 

Kodi Jarvis in Android.

Thanks for your efforts.

![screenshot_2018-01-13-11-22-48](https://user-images.githubusercontent.com/7310069/34902438-49f524f0-f856-11e7-995f-35fb9b54892e.png)

**Comment by Gujal00** [comment]
Okay problem seems to be specific to Kodi 16 on Android. Will fix and release an update

**Comment by yesosuresh** [comment]
Issue resolved. Thank you very much.
