### ISSUE TITLE
Deccan Delight Failed with 1.5.0 in 16.1 Jarvis

### ISSUE THREAD

**Issue by SunFloWeR15** [Gujal00/GujalKodiWork#25]
Hello, Looks like DeccanDelight on 16.1 Jarvis is broken completely with new version 1.5.0, It stopped  working after upgrade from 1.4.9. Please look into this. Thanks..

**Comment by Gujal00** [comment]
No point reporting error without attaching a log file. Will fix when someone posts a log file. Closing this as there are already two other issues opened for the same problem
