### ISSUE TITLE
Unable to open Ozee->shows

### ISSUE THREAD

**Issue by pavanpalaksha** [Gujal00/GujalKodiWork#27]
21:59:01.294 T:1946071712   ERROR: GetDirectory - Error getting plugin://plugin.video.deccandelight/?action=4&iurl=http%3a%2f%2fwww.ozee.com%2f%2fshows%2fall&site=ozee
21:59:01.296 T:1946071712   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.deccandelight/?action=4&iurl=http%3a%2f%2fwww.ozee.com%2f%2fshows%2fall&site=ozee) failed
21:59:05.690 T:1411380144  NOTICE: ResolveURL: Initializing ResolveURL version: 5.0.06
21:59:06.689 T:1411380144  NOTICE: script.module.youtube.dl: youtube_dl core version: 2017.12.31
21:59:23.269 T:1411380144  NOTICE: ResolveURL: Initializing ResolveURL version: 5.0.06
21:59:24.307 T:1411380144  NOTICE: script.module.youtube.dl: youtube_dl core version: 2017.12.31
22:00:34.395 T:1544819632  NOTICE: ES: Client  from ::ffff:192.168.0.181 timed out
22:10:10.845 T:1946071712   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
22:10:14.072 T:1858069424  NOTICE: ResolveURL: Initializing ResolveURL version: 5.0.06
22:10:15.095 T:1858069424  NOTICE: script.module.youtube.dl: youtube_dl core version: 2017.12.31
22:10:18.442 T:1858069424  NOTICE: ResolveURL: Initializing ResolveURL version: 5.0.06
22:10:19.472 T:1858069424  NOTICE: script.module.youtube.dl: youtube_dl core version: 2017.12.31
22:10:20.269 T:1858069424   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'findAll'
                                            Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/plugin.video.deccandelight/main.py", line 858, in <module>
                                                router(sys.argv[2][1:])
                                              File "/home/pi/.kodi/addons/plugin.video.deccandelight/main.py", line 840, in router
                                                list_top(params['site'],params['iurl'])
                                              File "/home/pi/.kodi/addons/plugin.video.deccandelight/main.py", line 518, in list_top
                                                menu,mode = cache.cacheFunction(scraper.get_top,iurl)
                                              File "/home/pi/.kodi/addons/script.common.plugin.cache/lib/StorageServer.py", line 570, in cacheFunction
                                                ret_val = funct(*args)
                                              File "/home/pi/.kodi/addons/plugin.video.deccandelight/resources/scrapers/ozee.py", line 52, in get_top
                                                items = mdiv.findAll('option', {'data-type':'lang'})
                                            AttributeError: 'NoneType' object has no attribute 'findAll'
                                            -->End of Python script error report<--
22:10:20.668 T:1946071712   ERROR: GetDirectory - Error getting plugin://plugin.video.deccandelight/?action=4&iurl=http%3a%2f%2fwww.ozee.com%2f%2fshows%2fall&site=ozee
22:10:20.670 T:1946071712   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.deccandelight/?action=4&iurl=http%3a%2f%2fwww.ozee.com%2f%2fshows%2fall&site=ozee) failed

**Comment by abezombie** [comment]
Same issue since 2 days

**Comment by Gujal00** [comment]
Website layout has changed. Give it a few days for the website layout to be completed and I will look at the scraper. Currently lot of links on the website are not working

**Comment by zeekd** [comment]
Any ETA on when this will be fixed?

**Comment by Gujal00** [comment]
whenever the webpage `http://www.ozee.com/shows/all` gets fixed. Until then nothing can be done on the addon
