### ISSUE TITLE
New Site scrapper request

### ISSUE THREAD

**Issue by ftpravi** [Gujal00/GujalKodiWork#28]
Hi, Could you please add the below sites. Thy are good source of watching Telugu tv serials/shows.
[https://www.manatelugumovies.net/](url)
[https://www.teluguflame.net/category/serials/](url)
[http://manatelugu.com/category/telugu-serials/](url)

probably all of them lead to a single source for showing serials.

**Comment by Gujal00** [comment]
Mana Telugu added in DD 1.5.6
https://github.com/Gujal00/GujalKodiWork/commit/72a11503308b983bdaa371f7e1bc93aae5dbc92e
