### ISSUE TITLE
TMV Scraper not working, and please have swiftstreamz channels added

### ISSUE THREAD

**Issue by sandyriverr** [Gujal00/GujalKodiWork#29]
Hello,
your wonderful efforts are really appreciated. Can you please add swiftstreamz channels and more TMV tamil channels please. The Adthiya channel in TMV stopped working too.

Thank you.

**Comment by Gujal00** [comment]
Will take a look at tmvplay

Sorry, won't touch swiftstreamz as including those channels was what casued zem addon developer to be sued.

**Comment by sandyriverr** [comment]
Thanks for responding. Appreciate you looking into the issue. Thoptv also channels dont work.

**Comment by Gujal00** [comment]
Please raise one issue per scraper.
TMVPlay fixed in https://github.com/Gujal00/GujalKodiWork/commit/8d8e292f60acaad9f9448ef7d2bb1bc3adcc5f5a

**Comment by sandyriverr** [comment]
Thanks for fixing. Will remember that next time
