### ISSUE TITLE
APK Land Live Tamil tv and VOD not working

### ISSUE THREAD

**Issue by ssarava9** [Gujal00/GujalKodiWork#3]
Hi Gujal,

APK land scraper for live tv and VOD not working, can you please fix it ?

**Comment by Gujal00** [comment]
live tv domain has changed, will take a look
VOD is working fine

**Comment by Gujal00** [comment]
Fixed in [https://github.com/Gujal00/GujalKodiWork/commit/3fe9173d9953a22b2d065ea771d47c8eecef944b](url)

**Comment by ssarava9** [comment]
Thanks Gujal for the effort.

Regards
Kumar

**Comment by ssarava9** [comment]
Hi Gujal,

APK land VOD not working, appreciate your help.

Thanks

**Comment by Gujal00** [comment]
please open a new issue so that it can be tracked

**Comment by Gujal00** [comment]
Next time open a new issue instead of commenting in an old closed issue.

Fixed in https://github.com/Gujal00/GujalKodiWork/commit/fc95ffc4c143c14a4769fea28e74ac8a882e13f3

**Comment by ssarava9** [comment]
Sure, will do, thanks
