### ISSUE TITLE
Request to integrate Einthusan into Deccan delight

### ISSUE THREAD

**Issue by crazyontech** [Gujal00/GujalKodiWork#3]
As you are aware Einthusan is one of the reliable sources for Indian Movies. Will it be possible to integrate Einthusan into the Deccan Delight addon?

**Comment by Gujal00** [comment]
Please request enhancements and addition through the official thread on the TV add-ons forum
https://forums.tvaddons.ag/addon-releases/49105-deccan-delight-indian-entertainment-11.html

Einthusan are still revamping their website and haven't released the api yet. Will look at it once it is available
