### ISSUE TITLE
Repo not working

### ISSUE THREAD

**Issue by Express2018** [Gujal00/GujalKodiWork#32]
Hi, I downloaded the latest Repo of 1.7 and installed it but it shows could not connect to the Repository error while trying. Please help to fix. Thanks.

https://github.com/Gujal00/GujalKodiWork/releases/download/1.7/repository.gujal-1.7.zip

**Comment by Gujal00** [comment]
Can't replicate the problem, working fine on the couple of machines that I tested with.
