### ISSUE TITLE
issues with playing video on high speed fiber (up to 700 Mbps)

### ISSUE THREAD

**Issue by Coby21** [Gujal00/GujalKodiWork#33]
Hi 
I've recently upgraded my internet speed from 100Mbps to gigantic speed (700 - 900 Mbps download).
Initially hindi tv videos (from desi tashan) (speedwatch.us, tune.pk, watchvideo18.us) worked fine, but recently they stop nearly every minute and goes into buffering for 5-10 minutes before playing for another 2 minutes, then stops for buffering.
I am trying to work out if this is internet issue or kodi issue.
Any advice will be great.

**Comment by ftpravi** [comment]
did u try loading those websites in a browser and see if it buffers too?

**Comment by Coby21** [comment]
Hi, Yes played on windows 7, does not buffer as much as it does on Android TV (Kodi 17.6). Tune.pk played flawlessly on web browser but on kodi it constantly buffers.

**Comment by Gujal00** [comment]
Usually Android TV Boxes have very poor wi-fi aerials. The buffering has nothing to do with Kodi, if the stream is 4Mbps and if the wifi can't sustain such speeds, of course you will see buffering.
As a trial, connect the Android TV to wired Ethernet and check the performance.
The fact that you are seeing buffering even from a browser on Windows, is not promising

**Comment by Coby21** [comment]
Thanks for advises.
The issue actually lied in the T95ZPlus android tv box, had to do factory reset and reload my apps. Works fine now, however, there are some sites Deccan Delight which do have slow speed source.
