### ISSUE TITLE
New channels request

### ISSUE THREAD

**Issue by sandyriverr** [Gujal00/GujalKodiWork#34]
Hi,
First of thank you for maintaining this addon for us.
Can you please add Jaya tv and Jaya movies channels in TMV play please. I ask because they seem to have the most stable servers and have very good quality with little or no buffering at all.

Thanks again.

**Comment by Gujal00** [comment]
tmvplay dont have those channels that you mention above. There are only 11 channels on site and all are listed and working in DD. Closing this for now
