### ISSUE TITLE
Request for new sites

### ISSUE THREAD

**Issue by janu1988** [Gujal00/GujalKodiWork#37]
Hi Bro, please check this sites if you can add them it will be great. 
`www.voot.com` ( vod for colors channels, this site works only with Indian vpn)
`http://lycatvmusic.com`

Thanks bro!

**Comment by plikmuny** [comment]
Deccan delight is down

**Comment by plikmuny** [comment]
Can we have a new website full of latest hindi movies?  It's name is watchonlinemovies.com.pk

**Comment by plikmuny** [comment]
Can we have a new website full of latest hindi movies?  It's name is www.watchonlinemovies.com.pk

**Comment by j6face** [comment]
hi, there is a website called www.biggbosstamil.net
possible to include it as well?  it includes COLOR TV channel as well.

**Comment by Gujal00** [comment]
@plikmuny `www.watchonlinemovies.com.pk` will be in DD 1.6.4 release
@j6face `www.biggbosstamil.net` will be in DD 1.6.4 release

**Comment by Gujal00** [comment]
@janu1988 
Voot addon released. Install from my repository

**Comment by plikmuny** [comment]
Thanks for all your hard work. i really appreciate you fulfilling our requests.
I want to request you one more side to add.
ist yaartv.tv. 
http://yaartv.tv/Hindi-Serial/show/116736/Indian-Idol

Can you pls do it for us pls. Thanks

**Comment by Gujal00** [comment]
@plikmuny Please do not add comments to an already closed issue. Open a new issue so that it shows up on my pending list
