### ISSUE TITLE
Deccan Delight is down 

### ISSUE THREAD

**Issue by plikmuny** [Gujal00/GujalKodiWork#38]
Hi, deccan delight is giving error since yesterday. I am not able to access it.  Plus fix it soon

**Comment by Gujal00** [comment]
What version of DD? Post the kodi log so that I can debug. Just saying it doesn't work isn't helpful

**Comment by plikmuny** [comment]
Here is the link to error log once I open ozee to watch TV shows. 
[]https://ufile.io/guay3(url)

**Comment by Gujal00** [comment]
So Ozee scraper is broken and you are reporting DD is down, Not Fair. Also you can see that there are already two issues open for Ozee #30 and #27 and I have also responded why it can't be fixed yet. Why keep opening more issues for the same problem? Will close this issue for now
