### ISSUE TITLE
Fix scrapers

### ISSUE THREAD

**Issue by redclam** [Gujal00/GujalKodiWork#39]
tmvplay is not working
Also, mhdtv tamil links (sun tv, sun music etc.) are not working.
Can you pls help?

**Comment by Gujal00** [comment]
tmvplay changed domains, fix will be in next release.
mhdtv is complex, some of the streams they host are overloaded and timeout. Doesn't seem to be a coding issue. Will investigate

**Comment by Gujal00** [comment]
Fixed in https://github.com/Gujal00/GujalKodiWork/commit/9ce2242960a8c606529ab5497138e75e09084abd

**Comment by redclam** [comment]
Thank you so much!!!!
