### ISSUE TITLE
Thoptv

### ISSUE THREAD

**Issue by mujunk** [Gujal00/GujalKodiWork#40]
I know Thoptv has been very volatile lately. Do you plan to support the site now?
They seem to have come up with some neat chrome extensions to permit VPN usage.

**Comment by Gujal00** [comment]
Basically it needs VPN to India as Jio TV have implemented geo-restriction of their streams to Indian IP addresses only.
So If you have VPN to India, thoptv will work. Nothing can be done inside Kodi for that.
