### ISSUE TITLE
RadiosIndia.com issue

### ISSUE THREAD

**Issue by elephant14** [Gujal00/GujalKodiWork#43]
Hi. Getting an error when trying load Tamil section. Other sections works/loads fine. Please have a look. Thanks

**Comment by Gujal00** [comment]
Bad coding on website for Sigaram FM, you can see that the title is not listed on the website
Will work around it and release a new version soon.

**Comment by Gujal00** [comment]
Fixed in https://github.com/Gujal00/GujalKodiWork/commit/ad2f4480a75f7baa1507edc1e6144506a67d6bde
Get version 0.2.0

**Comment by elephant14** [comment]
Thanks again
