### ISSUE TITLE
MHDTV not working - DD 1.5.5

### ISSUE THREAD

**Issue by redclam** [Gujal00/GujalKodiWork#44]
ERROR: GetDirectory - Error getting plugin://plugin.video.deccandelight/?action=1&site=mhdtv

**Comment by Gujal00** [comment]
Yes cloudflare have changed the protection, as MHDTV uses cloudflare, would need to be fixed.

**Comment by Gujal00** [comment]
Fixed in DD 1.5.6 https://github.com/Gujal00/GujalKodiWork/commit/72a11503308b983bdaa371f7e1bc93aae5dbc92e
