### ISSUE TITLE
Deccan Delight installation steps - fire tv stick

### ISSUE THREAD

**Issue by johnakash** [Gujal00/GujalKodiWork#45]
Could you please tell me the latest steps to configure Deccan Delight in fire tv stick?

**Comment by redclam** [comment]
download the zip file and follow instructions here
https://seo-michael.co.uk/how-to-push-zip-files-to-fire-stick-with-adbfire/

**Comment by johnakash** [comment]
Thanks for the response, Could you please confirm if we need to use the zip file from "https://github.com/Gujal00/GujalKodiWork/blob/master/zips/repository.gujal/repository.gujal-1.7.zip"  is the correct zip?

**Comment by johnakash** [comment]
Those steps worked well. Please find the necessary steps in short below

- Download zip file from the [GujalRePo](https://github.com/Gujal00/GujalKodiWork/blob/master/zips/repository.gujal/repository.gujal-1.7.zip)

- Steps to install repository add-on from zip: https://seo-michael.co.uk/how-to-push-zip-files-to-fire-stick-with-adbfire/

- Enabling Decaan delight add-on: https://www.youtube.com/watch?v=GUCiMtDwBIc

**Enjoy the Decaan Delight now!!!**
