### ISSUE TITLE
DD 1.5.5 thop tv no channels 

### ISSUE THREAD

**Issue by sandyriverr** [Gujal00/GujalKodiWork#46]
Thop tv has empty channels in all the language classifications

**Comment by Gujal00** [comment]
Will take a look, the site has been changing a lot recently so was waiting for it to settle.

**Comment by Gujal00** [comment]
Site changed drastically including requiring authentication.
Removed from DD

**Comment by sandyriverr** [comment]
Hi gujal,
Thanks for looking into it. I messaged the thop tv people and they did say
that they have a log in system now. But the site s still freefor all. All
each person needs to do is registerand get a log in to view the channels.

Thanks.
