### ISSUE TITLE
Deccan delight not working

### ISSUE THREAD

**Issue by kiwi81** [Gujal00/GujalKodiWork#47]
Deccan delight add-on 1.5.5 broken......

**Comment by Gujal00** [comment]
not much useful info there. What is not working? DD is a multi scraper addon, which scraper is broken other than the already acknowledged ones such s Ozee, MHDTV, Thoptv and HifyTV.

**Comment by kiwi81** [comment]
Hi thanks for your email...... Great service you doing.... Deccan delight
not at all working crashing saying check log for info..... But unable to
check log....thanks again for the amazing add-on entertained us for long
time.....

Kind regards,
Sanu Simon.

**Comment by Gujal00** [comment]
Are you not able to start DD? upload the kodi log after DD fails to pastebin and post the link here.
It is some issue specific to your system, I tested and is working fine on multiple systems
