### ISSUE TITLE
manatv telugu catchup

### ISSUE THREAD

**Issue by ftpravi** [Gujal00/GujalKodiWork#48]
the manatv scrapper(ManaTelugu ) is not loading the current shows and is showing the old content(currently showing content before 25th April). To resolve this I have to manually delete the cache of the ad-don entirely and a fresh content is loaded with today's shows. But this scenario repeats until i delete the ad-don cache to reload the current shows. Changing the cache options to '0' or '1' is not having any effect. Its the same behavior for two different version of windows and an android tv box.

PS: Tried deleting the cache on my windows computer where kodi is installed. Haven't tried the cache clearing on the android TV box.

**Comment by Gujal00** [comment]
In addon settings, there is a setting for the cache period, try dropping it to 8 hours.
The cache is actually located in userdata/addons/plugin.video.deccandelight folder.
Will look at adding an option to clear cache inside the addon in the release.

**Comment by ftpravi** [comment]
Yes, thats the setting I am talking about.

Additionally found out that the links from the cache have changed and since the links are not updated here they are failing to play the video. Checking the site for that particular date shows a different video link, perhaps they are updating the video links after some time.

Will having a no cache solve the issue for this scrapper? 

 Current log attached for the videos failing. 

[kodi.log](https://github.com/Gujal00/GujalKodiWork/files/1965452/kodi.log)

**Comment by Gujal00** [comment]
DD 1.5.7 released https://github.com/Gujal00/GujalKodiWork/commit/9a354b859edf0bd4118136ad11abb0790e90d917
Has a Clear Cache option in the main menu. selecting it dumps the current cache

Test and report if still issues

**Comment by ftpravi** [comment]
Clear cache option clears the cache and i can load the shows of current day. You can close the ticket now. Thank you so much for a quick turn around.
