### ISSUE TITLE
New Episodes not showing

### ISSUE THREAD

**Issue by vickysuman** [Gujal00/GujalKodiWork#49]
Hello,
From last week, may be after new update I can not see the new episodes listed under sony tv under Yodesi. I tried to reinstall the repositary and the addon Deccan delight, but it did not helped. But if i uninstall Kodi and then install the addon again than the new episodes are shown but again only for one day not next day. Kindly help. But on the top great appreciation for the hard work. God bless the developer. 
Thanks

**Comment by Gujal00** [comment]
Will release a new version with option to Clear the cache in the main menu. same as #48

**Comment by vickysuman** [comment]
Thanks for the reply, will keep an eye for the new release.

**Comment by Gujal00** [comment]
DD 1.5.7 released https://github.com/Gujal00/GujalKodiWork/commit/9a354b859edf0bd4118136ad11abb0790e90d917
Has a Clear Cache option in the main menu. selecting it dumps the current cache

Test and report if still issues
