### ISSUE TITLE
Old dates

### ISSUE THREAD

**Issue by kuku45** [Gujal00/GujalKodiWork#50]
When I tried to watch hindi serials on Yo desi and desi tashan new dates are not shown. These are old dates. After April 27 no new shows are shown

**Comment by Gujal00** [comment]
Update to DD 1.5.7 and use "Clear Cache" in the main menu whenever you dont see new stuff.

**Comment by kuku45** [comment]
Thanks. Where to get DD1.5.7. Where to find the main menu in kodi?

Regards,
Yogesh Malhotra,

**Comment by Gujal00** [comment]
Install the repository and it will autoupdate to 1.5.7
Repository has always been here - https://github.com/Gujal00/GujalKodiWork/releases/download/1.7/repository.gujal-1.7.zip

**Comment by kuku45** [comment]
Thanks. This works

Regards,
Yogesh Malhotra,
