### ISSUE TITLE
yo desi not working

### ISSUE THREAD

**Issue by rrosajp** [Gujal00/GujalKodiWork#52]
``class yodesi(Scraper):
    def __init__(self):
        Scraper.__init__(self)
        self.bu = 'http://www.yodesi.to/'``

it change to 
``class yodesi(Scraper):
    def __init__(self):
        Scraper.__init__(self)
        self.bu = `'http://www.yodesi.tv/'`

**Comment by Gujal00** [comment]
There is an automatic redirection in place by Yodesi to redirect from .to to .tv.
It is still working in the addon with the redirect.
Will change it in the next release as it is not broken yet,

**Comment by rrosajp** [comment]
thanks for reply
