### ISSUE TITLE
Deccan Delight 1.5.7 not updating latest movies

### ISSUE THREAD

**Issue by saravsoftnet** [Gujal00/GujalKodiWork#54]
Deccan delight just shows only the old content which already there, i updated the latest version as well still has same issue. It just display old movie list and old tvs vod dates not updated with latest one. please take a look

**Comment by Gujal00** [comment]
Has already been answered on #50 and #53 
Use clear cache option

**Comment by saravsoftnet** [comment]
clearing cache doesn't resolve the issue, still shows only old content, i restarted the app, i dont find any issue with tamilgun app, it is updating with latest movies as expected issue only with deccan delight, please take a look

**Comment by saravsoftnet** [comment]
i un install entire kodi and resintall it then deccan delight installed then only issue resolved. but next day and day after the day when i check it still shows the dates of the day i installed after the days folders are not getting updated. Again i reinstall everything then it shows. i think there is a issue with deccan delight.

**Comment by Gujal00** [comment]
the cache is a single file called cache.db held inside the userdata\addon_data\plugin.video.deccandelight folder and gets deleted when clear cache option is selected. 
There is no need to reinstall Kodi.
What platform are you running it under and what version of Kodi

**Comment by Gujal00** [comment]
I have reverted to the caching mechanism in DD 1.5.9 as used in earlier versions. Should work in Android Jarvis as before.
