### ISSUE TITLE
 Deccan Delight not working 

### ISSUE THREAD

**Issue by saravanavel28** [Gujal00/GujalKodiWork#60]
Error:addon:extension is not currently supported for service addon

**Comment by Gujal00** [comment]
That is nothing to do with Deeccan Delight as it does not have any service modules

**Comment by Gujal00** [comment]
please upload the logfile and provide the link. It is diffiicult to diagnose without it, as Deccan Delight 1.5.8 works fine on Kodi 17.6 Windows 8&10 and MXIII+ Android 5.1 (the only platforms that I have)
