### ISSUE TITLE
Deccan Delight APK Land & Vod Channels not working

### ISSUE THREAD

**Issue by saravsoftnet** [Gujal00/GujalKodiWork#61]
APK land and VODs are not playing in KODI, it shows "one or more items failed to play. Check the log for more information about this message" dialogue box shows, this error shows even after the update of 1.5.9. Please take a look

**Comment by Gujal00** [comment]
I can't see any issue on the addon other than that some streams that do not work on the addon also do not work on the apkland website.
Please upload your log when reporting issues so that it can be debugged

**Comment by saravsoftnet** [comment]
Hi
Here is the error i am getting
19:42:27.540 T:1717334784   ERROR: OpenDemuxStream - Error creating demuxer
19:42:27.540 T:1717334784  NOTICE: CVideoPlayer::OnExit()
19:42:27.543 T:1925659136   ERROR: Playlist Player: skipping unplayable item

**Comment by Gujal00** [comment]
Please post the full log. The snippets that you have posted are of no use as that is from kodiplayer and not deccan delight. As I said earlier I just tested applaud vod and whatever works on their website works on the addon

**Comment by saravsoftnet** [comment]
how to get the deccan delight log
please send me the steps

**Comment by Gujal00** [comment]
Kodi log uploader addon from official kodi repo will do it

**Comment by saravsoftnet** [comment]
[https://paste.kodi.tv/ruyuzecuwo](url) log info available here

**Comment by saravsoftnet** [comment]
can you paste the source vod location to check before raise any issue

**Comment by Gujal00** [comment]
VOD is not presented as a website anymore, you need the android app
http://apkland.tv/vod/
