### ISSUE TITLE
Desi Tashan Stopped

### ISSUE THREAD

**Issue by vickysuman** [Gujal00/GujalKodiWork#62]
Hello Gujal,
Thanks for your efforts. Desi Tashan has stopped working, Please check when you have time. Thanks

**Comment by Gujal00** [comment]
Site is gone. 
```http://www.desi-tashan.ch/```
Will see if it comes back

**Comment by vickysuman** [comment]
Yes, its not working, so was checking http://www.desitashan.tv
May be they have changed the URL.
Thanks.

**Comment by Gujal00** [comment]
Thanks, have released DD1.6.1 with the domain change
