### ISSUE TITLE
New Scrapper Request

### ISSUE THREAD

**Issue by ftpravi** [Gujal00/GujalKodiWork#63]
Can you please add "https://www.teluguflame.net/category/serials/" 

this is a telugu catchup site and probably the videos are hosted on dailymotion.

**Comment by Gujal00** [comment]
It is a bad website, lots of empty links and so on
Anyway, I have added it in DD 1.6.2 https://github.com/Gujal00/GujalKodiWork/commit/ca230f408876dbca29261af01336ab056dbc6a78
But if something is not working, check on the website first and then report
