### ISSUE TITLE
Issues with ManaTelugu and telugu flame

### ISSUE THREAD

**Issue by rkonda1** [Gujal00/GujalKodiWork#64]
Thanks for the hardwork. Mana Telugu and Telugu flame doesn't have any content.. Am i missing anything in installation..

**Comment by Gujal00** [comment]
I dont see any issue on Android or Windows. Please use the Kodi Log Uploader addon to upload your log and give me the link here to see why it is not working for you

**Comment by ftpravi** [comment]
I am seeing issue with teluguflame
in the below URL I can see the video using my chrome web browser but not with kodi

http://videos.telugunxt.com/trk-16-06-18/

Additionally no video plays with teluguflame. I am attaching the log file , It doesnt wok on my windows 7/ 10 installations and my android Box as well.
[kodi.log](https://github.com/Gujal00/GujalKodiWork/files/2109508/kodi.log)

**Comment by Gujal00** [comment]
@ftpravi 
Yes, that is an expected error as the ResolveURL needs an update. You have the latest released version of ResolveURL but that does not have the fix required to play telguflame videos. You need an updated waaw.py from the ResolveURL git for this to work.

@rkonda1 was reporting no content was showing up in both manatelugu and teluguflame scraper, which is different from your issue of not playing teluguflame videos, which will work when ResolveURL is updated or you manually pull in the waaw.py fix
