### ISSUE TITLE
Tamil Yogi not pulling menu

### ISSUE THREAD

**Issue by SunFloWeR15** [Gujal00/GujalKodiWork#68]
Hello Friend, 

Looks like get_menu() - re.findall() is broken (may be regex string) - please look into it.. not pulling the menu. Only **Search** is retrieved not the menus.

Platform: Android
Media Center: Kodi 17.6

**Comment by Gujal00** [comment]
Nothing wrong with regex
Tamil Yogi have enabled Cloudflare DDOS protection, will have to recode the site access.

**Comment by SunFloWeR15** [comment]
Thanks for the update.. kindly look into it..

**Comment by Gujal00** [comment]
Fixed in DD1.6.3
