### ISSUE TITLE
New site scraper request

### ISSUE THREAD

**Issue by sandyriverr** [Gujal00/GujalKodiWork#69]
Can you please add `www.tamildhool.com`
This site has all allthe vijay tv shows similar to hotstar

Thanks

**Comment by plikmuny** [comment]
Can you also add http://yaartv.tv/Hindi-Serial/show/116736/Indian-Idol pls.
it has good collection in good Quality and the links open very fast and they are stable also.
Thanks

**Comment by Gujal00** [comment]
Tamildhool scraper code is ready. Will be in the next release

**Comment by Gujal00** [comment]
DD 1.6.6 released
