### ISSUE TITLE
Deccan delight scraper update

### ISSUE THREAD

**Issue by akhildara123** [Gujal00/GujalKodiWork#7]
In deccan delight update scraper of Movierulz please  the domain of the site changed from .mn to .ms please update it, I couldn't able to use it on my Kodi now, it has been so long,
Thank you

**Comment by Gujal00** [comment]
Seems to be working fine for me.
Is the scraper really broken?

**Comment by akhildara123** [comment]
What's the problem actually is, .mn site blocked by almost all isp, it usually redirect to  .ms.. So, for me  .mn blocked almost all India it is blocked.. So, I am requesting to change the domain 😀

**Comment by Gujal00** [comment]
Done , new version released
