### ISSUE TITLE
DD 1.6.3 install failing

### ISSUE THREAD

**Issue by SunFloWeR15** [Gujal00/GujalKodiWork#70]
Hi, the fix provided for the DD (fix tyogi cloudflare ddos issue) is failing to install on Android Kodi 16.1 and 17.6, is it the phython compatibility issue? Will mygica picks this one..Pls suggest.. thanks for the help.

**Comment by Gujal00** [comment]
Cloudflare fix was already used by others such as mhdtv in the addon and is not new. Can you enable debug log and then try to install dd1.6.3 and then upload the log using Kodi log uploader and give me the link?
I tested it on Android and windows 17.6 and works fine

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by SunFloWeR15** [comment]
Please close the issue, I reinstalled again now and it went through..not sure what was causing this.. thank you!
