### ISSUE TITLE
Deccan Delight 1.6.3 :: Unable to Play Movie

### ISSUE THREAD

**Issue by kathirudeen** [Gujal00/GujalKodiWork#71]
Could you help to fix this error!!!
My Kodi Log is....
<snip> **Please do not post logs here**
12:49:08.228 T:509460919376   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.deccandelight/?action=9&iurl=http://fastplay.to/embed-1clmuuskhdsz.html]
12:49:08.228 T:509460919376   DEBUG: Playlist Player: one or more items failed to play... aborting playback

**Comment by Gujal00** [comment]
Please do not post log file here. Instead upload the log file using Kodi logfile uploader (from official kodi repository) and then just post the link that it provides over here.

Anyway from the log, it is not a Deccan Delight issue, it seems to be that ResolveURL is resolving it correctly but Kodiplayer not able to play.
Can you check if the link`http://fastplay.to/embed-1clmuuskhdsz.html` work for you in browser. I do not see any issue with that link for me in browser or Kodi

**Comment by kathirudeen** [comment]
thanks
