### ISSUE TITLE
Deccan Delight - Tamil Yogi Not working

### ISSUE THREAD

**Issue by shu160506** [Gujal00/GujalKodiWork#72]
Tamil Yogi not working in the latest repository version.  I am running on firestick.  Deccan delight version 1.6.4.  Please help

**Comment by SunFloWeR15** [comment]
Yes, in android platform too, there are no links displayed (except Search link) - looks like broken. Kindly look into it.

**Comment by Gujal00** [comment]
TamilYogi and Mersalaayitten changed domains. Both fixed in DD 1.6.5
