### ISSUE TITLE
YoDesi catchup tv not working

### ISSUE THREAD

**Issue by jonanthaon** [Gujal00/GujalKodiWork#73]
So there is a problem with Yodesi specifically with &TV, on HindiLinks4U &TV works but if possible can you fix &TV under the Yodesi section. See gif below.
![yodesi](https://user-images.githubusercontent.com/40902218/42402018-6552047e-8146-11e8-98ab-50bec91ab7db.gif)

**Comment by Gujal00** [comment]
Yodesi have changed the url for & TV. WIll fix in the next release

**Comment by Gujal00** [comment]
DD 1.6.6 released
