### ISSUE TITLE
New site scraper request : yaartv.tv

### ISSUE THREAD

**Issue by plikmuny** [Gujal00/GujalKodiWork#74]
Hi Final, can you please add this website to your addon plz.
[www.yaartv.tv](url)
It has all the catch up videos from most of the channels.
Pls add it in your next release.
Thanks in advance

**Comment by Gujal00** [comment]
Yep, the scraper code is ready. Will be in the next release

**Comment by plikmuny** [comment]
Thanks a lot Gujal.

**Comment by Gujal00** [comment]
DD 1.6.6 released
