### ISSUE TITLE
Teluguflame issue

### ISSUE THREAD

**Issue by ftpravi** [Gujal00/GujalKodiWork#77]
I am facing a strange issue where only some times the player is unable to play the video. This happens only in some days and the rest of the days there is no issue playing the video. I have attached the kodi log.

The issue has happened today and the url for today's link is http://videos.telugunxt.com/trk-12-07-18/

[kodi.log](https://github.com/Gujal00/GujalKodiWork/files/2190873/kodi.log)

**Comment by Gujal00** [comment]
From your log
`ResolveURL: ResolverError Error - From: waaw Link:`

I mentioned earlier that hqq/netu/waaw is broken in the released resolveurl and will work when jsergio releases a new version
In the mean time to get it working you have to copy the waaw.py from jsergio's github plugin folder to your machine.
It works fine once you update ResolveURL. [Screenshot here](https://i.imgur.com/NZtL1Cv.png)
