### ISSUE TITLE
Malayalam Links not working

### ISSUE THREAD

**Issue by shijucj7** [Gujal00/GujalKodiWork#78]
Hi, can you please check the Malayalam links. Both are not working.
If possible add: http://abcmalayalam.tv/

**Comment by Gujal00** [comment]
Both Olangal and Tormalayalam are working perfectly in the version from this repository. What version of DD are you running and are you able to access either of the above sites in a browser

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by shijucj7** [comment]
So sorry.. the problem happens when I use SPMC  apk (which runs on older version of Kodi).
When I try the latest one its working
