### ISSUE TITLE
Deccan Delight Tamil Yogi and VOD

### ISSUE THREAD

**Issue by saravsoftnet** [Gujal00/GujalKodiWork#79]
Hi Team,

Thank you for your timing response and working for us. Just like to know Tamil Yogi's tamil dubbed folder just has movie folder but doesn't have movie file.

In Vod, Sun TV all dates folder including programs are working fine, but K TV folder created every day folder but doesnt have any programs. can you please look into it if you can.

Thanks in advance for look up.

Saravanan

**Comment by Gujal00** [comment]
1. TamilYogi dubbed movies needs a new plugin for ResolveURL, have done a PR for that and will be supported when ResolveUrll new version is released. Not an issue with Deccan Delight. 

2. Vod KTV is a issue with the site itself. Not an issue with Deccan Delight.
