### ISSUE TITLE
live tv section not working properly 

### ISSUE THREAD

**Issue by nikhilmahant** [Gujal00/GujalKodiWork#8]
sir first i would like to thank you for your great work..🙂
everything els work properly but when i open any live tv section such as MHDTV or Abroad India..i get error like unable to play...so i thought of visiting the sites directly and it works in the browser...only thing is i have to put "HTTPS" then ill get access...so can you please implement this in Deccan delight addon? so that it gets unblocked from isp...thank you again sir

**Comment by Gujal00** [comment]
MHDTV is now enforcing login and not providing free access to the streams. So can't do anything about it until they change that stance
Both Abroadindia and MHDTV do not have a SSL cert issued to them. So I can't turn on HTTPS to them

So nothing can be done at the moment, unfortunately

**Comment by nikhilmahant** [comment]
oh thats ok sir...and thank you for the great addon..:-)

**Comment by Gujal00** [comment]
@nikhilmahant 
MHDTV fixed in DD 1.4.8 release
Also NexTV and HyfyTV are added

**Comment by nikhilmahant** [comment]
thanks a lot sir..now everything is working properly.... really appreciate your work....
