### ISSUE TITLE
Deccan Delight > Lyca Music Channel broken

### ISSUE THREAD

**Issue by SunFloWeR15** [Gujal00/GujalKodiWork#83]
Looks like Lyca Music TV link seems to be broken.. 'http://lycatvmusic.com/' - taking to AthavanTV.com.. kindly look into it... thanks

**Comment by Gujal00** [comment]
Website broken, Will fix it when the streams start working on the website.

**Comment by Gujal00** [comment]
Okay scraper is fixed for the new site layout. Will be part of the upcoming release

**Comment by Gujal00** [comment]
Fixed in https://github.com/Gujal00/GujalKodiWork/commit/9873f64b8be78d94fd0effa99b00f12c6fdf8cf2
Update to DD 1.6.7
