### ISSUE TITLE
Tamildhool broken

### ISSUE THREAD

**Issue by praveen12bnitt** [Gujal00/GujalKodiWork#84]
Deccan Delight is awesome. I am loving it. This week, tamildhool scrapper is broken. Can you please fix it ?

**Comment by Gujal00** [comment]
Yes Tamildhool website has changed and they have removed lot of content which was available before.
WIll wait and see if they bring back the full content.
For now search and gossip sections are working on tamildhool. So use it that way until they sort their website

**Comment by Gujal00** [comment]
Okay scraper is fixed for the new site layout. Will be part of the upcoming release

**Comment by praveen12bnitt** [comment]
Wow. That's quick.  Thank u.

**Comment by Gujal00** [comment]
Fixed in https://github.com/Gujal00/GujalKodiWork/commit/9873f64b8be78d94fd0effa99b00f12c6fdf8cf2
Update to DD 1.6.7
