### ISSUE TITLE
Request to add new site 

### ISSUE THREAD

**Issue by akhildara123** [Gujal00/GujalKodiWork#9]
I request you to add a new movie watching site   tmvplay. com.. In your deccan delight plugin 😊😊
It has many movies and also few live TV and expecting the content to increase..
Thanks in advance

**Comment by Gujal00** [comment]
Need at least one category with more than 2 pages to code pagination correctly. Will take a look when any category/genre has more than 50 entries

**Comment by akhildara123** [comment]
Thank you so much for taking time 😃😃, I think it'll be 50 in a category
around in a week or so

On 31-Oct-2017 2:01 PM, "Gujal" <notifications@github.com> wrote:

Need at least one category with more than 2 pages to code pagination
correctly. Will take a look when any category/genre has more than 50 entries

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Gujal00/GujalKodiWork/issues/9#issuecomment-340693613>,
or mute the thread

**Comment by Gujal00** [comment]
Will be in 1.3.8 release
